### PR TITLE
fix of header and conversation list is not dark

### PR DESCRIPTION
**Pull request by bussorenre**
thanks for  your  nice style and I use it.
I found a bug and fix it. I attach screenshot.

Browser: Chrome 77.0.3865.90
Operating System: macOS mojave 10.14.6

before:
before

aftet this commit:
after

please consider to merge this.
thank you.

### CODE REVIEW

**Comment by the-j0k3r** [comment]
@bussorenre Thank you for reaching out with this contribution.

This isnt really a bug, its intended to remain the original color as shown. The idea behind style is to only darken bright elements and some really bright colors and not to fundamentally change elements colors to gray/black.

I really didnt want to add opinionated styling, and if this pokes at your retinas, Ill have to think about it.

**Comment by the-j0k3r** [comment]
@bussorenre How would you feel if this was instead a darker purple for now?

Something like `#500056` or something along those lines instead of current `#7e0088`?

**Comment by the-j0k3r** [comment]
Actually having reviewed the disposition of the elements in actual page, I see why I went this way, probably unfinished job. Ill accept this change as is, thank you for your contribution.

Expect a new release in a minute. =)

**Comment by bussorenre** [comment]
Thank you mersing.
I prefer to unified color whichever #500056 and #7e0088.

**Comment by the-j0k3r** [comment]
Thanks again.

**Pull request merged**
